[main2]
; path to results (some kind of tracker workspace)
RESULT_PATH=./tracker/
; the '-y' kinda flag
ASK_BEFORE_FLOW_DELETE=False
DRAW_DETS=False
; 0: main, 1: main_d1, 2: main_d2, ...
MAIN_N=0
; switch to save trajectories on every selection step for vizualization/debug purposes
SAVE_TRAJECTORIES=True
; maximum number of extrapolation of trajectories (# of consecutive frames without detections for that trajectory (number of relative holes, essentially))
EXT_THR=5
; initial score of trajectory (when merge)
T_INIT_S=0.5
; maximum number of merged trajectories at once (to limit recursion depth)
MAX_N_TR_MERGE_ONCE=100
; use precomputed optical flow (set to False to calculate it on the go) (flows-path must be set)
USE_PRECOMPUTED=False
USE_PRECOMPUTED_FLOW=False
USE_PRECOMPUTED_FEAT=False
PRECOMPUTED_FLOW_PATH=./tracker/flow/
PRECOMPUTED_FEAT_PATH=./tracker/feat/
COMPUTE_OR_GET_TEST=not True
; main-specific:
SAVE_FEATURES=not True
RUN_ALL=not False
T_OFFSET = 1
; use sequences.ini
USE_INIT_FILE=True