[main2]
; path to results (some kind of tracker workspace)
RESULT_PATH=./tracker/
; the '-y' kinda flag
ASK_BEFORE_FLOW_DELETE=False
DRAW_DETS=False
; also include ground truth in detections (for analysis)
INCLUDE_GT=False
; 0: main, 1: main_d1, 2: main_d2, ...
MAIN_N=0
; switch to save trajectories on every selection step for vizualization/debug purposes (all trs)
SAVE_TRAJECTORIES=False
; save trajectories, that are used in final path (trs.p)
SAVE_PATH_TR=True
; path creation type
PATH_CREATION_TYPE=1
; maximum number of extrapolation of trajectories (# of consecutive frames without detections for that trajectory (number of relative holes, essentially))
EXT_THR=5
; initial score of trajectory (when merge)
T_INIT_S=0.5
; maximum number of merged trajectories at once (to limit recursion depth)
MAX_N_TR_MERGE_ONCE=100
; use precomputed optical flow (set to False to calculate it on the go) (flows-path must be set)
USE_PRECOMPUTED=False
USE_PRECOMPUTED_FLOW=False
USE_PRECOMPUTED_FEAT=False
PRECOMPUTED_FLOW_PATH=./tracker/flow/
PRECOMPUTED_FEAT_PATH=./tracker/feat/
COMPUTE_OR_GET_TEST=False
; main-specific:
SAVE_FEATURES=False
RUN_ALL=True
T_OFFSET = 1
; use sequences.ini
USE_INIT_FILE=True

; trajectory config
[tr]
; ratio between iou and visual score (used in getProbIV)
A1=0.9

[detan]
SEQUENCE=bird2
N=0.5